### ISSUE TITLE
fresh install ubuntu 18.0.4

### ISSUE THREAD

**Issue by hmatos-rogers** [jimboca/udi-poly-kasa#17]
Hi,
I've tried installing several times and after successfully getting past the python3.7/pip issues I am still unable to get the node server started.  The install.sh completes with no issues, but when I attempt to start the node server and consistently get, "polyinterface:write: No module named 'kasa'".

Your help is appreciated,

Heroildo

2021-04-03 13:04:24,801 MainThread polyinterface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2021-04-03 13:04:25,249 MainThread polyinterface      INFO     polyinterface:init_interface: Received Config from STDIN.
2021-04-03 13:04:25,249 MainThread polyinterface      INFO     __init__:<module>: UDI Polyglot v2 Interface 2.1.0 Starting...
2021-04-03 13:04:25,287 MainThread py.warnings        WARNING  warnings:_showwarnmsg: /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
2021-04-03 13:04:25,287 MainThread py.warnings        WARNING  warnings:_showwarnmsg: /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: Traceback (most recent call last):
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: File "./kasa-poly.py", line 11, in <module>
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: from nodes import Controller
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: File "/root/.polyglot/nodeservers/Kasa/nodes/__init__.py", line 7, in <module>
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: from .SmartDeviceNode    import SmartDeviceNode
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: File "/root/.polyglot/nodeservers/Kasa/nodes/SmartDeviceNode.py", line 8, in <module>
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: from kasa import SmartDeviceException
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: ModuleNotFoundError
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: :
2021-04-03 13:04:25,317 MainThread polyinterface      ERROR    polyinterface:write: No module named 'kasa'

**Comment by jimboca** [comment]
The install must not have been successful, try running the install.sh manually.

**Comment by jimboca** [comment]
No response, closing.
